services:
  web:
    build:
      context: ./
      dockerfile: ${_DOCKERFILE_PATH}
      target: ${TARGET_LOCAL}
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    hostname: localhost
    working_dir: ${WORK_DIR}
    restart: "no"
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:${WORK_DIR}
      - ~/.ssh:${WORK_DIR}/.ssh:ro
      - ~/.gcloud:${WORK_DIR}/.gcloud:ro
    # command: [ "tail", "-f", "/dev/null" ]  # 何もせずに起動
    command: [ "sh", "scripts/run.sh" ]
    env_file:
      - .env
      - dotenvs/.env.dev
