version: "3"
services:
  app:
    env_file:
      - .env
      - .env.dev
    build:
      context: ./
      dockerfile: ${DOCKERFILE_LOCAL_PATH}
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    hostname: localhost
    working_dir: ${WORK_DIR}
    restart: "no"
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:${WORK_DIR}
      - ~/.ssh:${WORK_DIR}/.ssh:ro
    entrypoint:
      - scripts/run.sh
