import os


API_URL_DEV = os.environ["API_URL_DEV"]
GOOGLE_APPLICATION_CREDENTIALS = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")

print(f"API_URL_DEV: {API_URL_DEV}")
print(f"GOOGLE_APPLICATION_CREDENTIALS: {GOOGLE_APPLICATION_CREDENTIALS}")
